// error page
GET http://localhost:3003/api/externalLink HTTP/1.1
Content-Type: application/json

###

// go instagram
GET http://localhost:3003/api/instagramLink HTTP/1.1
Content-Type: application/json

###

// go facebook
GET http://localhost:3003/api/facebookLink HTTP/1.1
Content-Type: application/json

###
// go tiktok
GET http://localhost:3003/api/tiktokLink HTTP/1.1
Content-Type: application/json

###
// go biografia
GET http://localhost:3003/api/biografiaLink HTTP/1.1
Content-Type: application/json

###
// go galery of services
GET http://localhost:3003/api/galeryLink?grupo=drawing HTTP/1.1
Content-Type: application/json

###

// send email
POST  http://localhost:3003/api/send-email HTTP/1.1
Content-Type: application/json

    {
      "from_email_address": "pepe@gmail.com",
      "subject": "pintura",
      "message": "offline"
    }

###

// get testimonios
GET http://localhost:3003/api/getTestimonios HTTP/1.1
Content-Type: application/json


###

// crear nuevo testimonio
POST  http://localhost:3003/api/createTestimonios HTTP/1.1
Content-Type: application/json

    {
      "comentario": "nuevo testimonio",
       "nombre": "alejandro",
       "ocupacion": "genio",
       "email": "alejo@gmail.com"
    }

###

###

DELETE http://localhost:3003/api/deleteTestimonio HTTP/1.1
Content-Type: application/json

{
  "id": "66979ac39b68b7d3dabdfca7",
  "email": "alejo@gmail.com"
}
###
