// error page
GET http://localhost:3003/api/externalLink HTTP/1.1
Content-Type: application/json

###

// go instagram
GET http://localhost:3003/api/instagramLink HTTP/1.1
Content-Type: application/json

###

// go facebook
GET http://localhost:3003/api/facebookLink HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3003/api/tiktokLink HTTP/1.1
Content-Type: application/json


###

// send email
POST  http://localhost:3003/api/send-email HTTP/1.1
Content-Type: application/json

    {
      "from_email_address": "pepe@gmail.com",
      "subject": "pintura",
      "message": "offline"
    }



